language: python
python:
  - "3.7"
cache: pip
env:
  global:
    - DISABLE_COLLECTSTATIC=1 
    - TELEGRAM_TOKE=token 
    - DATABASE_URL=sqlite:///:memory:
install:
  - pipenv install --dev
script:
  - make test
deploy:
  provider: script
  script: make deploy
  on:
    branch: master
